[package]
name = "rag-redis-mcp-server"
version.workspace = true
edition.workspace = true
authors = ["RAG-Redis Development Team"]
description = "MCP server for RAG-Redis system providing document ingestion, vector search, and memory management"
license = "MIT"

[dependencies]
# Core RAG system
rag-redis-system = { path = ".." }

# Async runtime
tokio.workspace = true
async-trait = "0.1"
futures = "0.3"

# JSON-RPC and MCP protocol
serde.workspace = true
serde_json = "1.0"

# Error handling and logging
thiserror = "2.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# I/O
tokio-util = { version = "0.7", features = ["codec"] }

# Utilities
uuid.workspace = true
chrono = { version = "0.4", features = ["serde"] }
url = "2.5"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.14"

[[bin]]
name = "rag-redis-mcp-server"
path = "src/main.rs"

[[example]]
name = "test_tool_execution"
path = "examples/test_tool_execution.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
