[package]
name = "gemma-cross"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "Cross-compilation utilities and build scripts for Gemma"
keywords = ["cross-compilation", "build", "ci", "deployment"]
categories = ["development-tools::build-utils"]

[[bin]]
name = "build-all-targets"
path = "src/build_all.rs"

[[bin]]
name = "package-releases"
path = "src/package.rs"

[dependencies]
# Build and deployment utilities
clap.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

# File system and path operations
walkdir = "2.4"
glob = "0.3"
tempfile.workspace = true

# Compression and archiving
flate2.workspace = true
tar = "0.4"
zip = "2.1"

# HTTP client for downloading dependencies
reqwest.workspace = true

# Process execution
tokio.workspace = true
tokio-process = "0.2"

# Cross-compilation detection
target-lexicon = "0.12"

# Build script utilities
cc = "1.0"
pkg-config = "0.3"

# Environment and system info
which = "6.0"
os_info = "3.7"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"
bindgen = { version = "0.69", optional = true }

[features]
default = ["auto-detect"]
auto-detect = []
bindgen = ["dep:bindgen"]

# Target-specific features for optimization flags
x86_64-optimizations = []
aarch64-optimizations = []
wasm-optimizations = []
