[package]
name = "rag-redis-demo"
version = "0.1.0"
edition = "2021"
description = "Standalone demo of RAG-Redis system concepts"

[dependencies]
# Core async runtime
tokio = { version = "1.45", features = ["full", "time"] }

# Serialization and JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
uuid = { version = "1.11", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Time utilities
time = "0.3"

[[bin]]
name = "rag_demo"
path = "src/main.rs"
