[package]
name = "gemma-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "High-performance Axum-based HTTP server for Gemma inference"
keywords = ["server", "http", "axum", "inference", "performance"]
categories = ["web-programming::http-server", "science"]

[[bin]]
name = "gemma-server"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
futures-util.workspace = true
async-trait.workspace = true

axum.workspace = true
axum-extra.workspace = true
tower.workspace = true
tower-http.workspace = true
hyper.workspace = true

serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true

anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true

clap.workspace = true
config.workspace = true
toml.workspace = true

# Server-specific dependencies
gemma-inference = { path = "../inference" }

# HTTP middleware and utilities
headers = "0.4"
mime = "0.3"

# Metrics and monitoring
metrics = "0.23"
metrics-exporter-prometheus = "0.15"

# Health checks and graceful shutdown
tokio-graceful-shutdown = "0.15"

# Rate limiting and security
governor = "0.6"
jsonwebtoken = "9.3"

# WebSocket support
tokio-tungstenite = "0.21"

# Compression
async-compression = { version = "0.4", features = ["tokio", "gzip", "brotli"] }

# TLS support
rustls = "0.23"
rustls-pemfile = "2.1"
tokio-rustls = "0.26"

[dev-dependencies]
tower-test = "0.4"
http-body-util = "0.1"
tokio-test.workspace = true
tempfile.workspace = true
criterion.workspace = true

[features]
default = ["metrics", "compression", "tls"]
metrics = ["dep:metrics", "dep:metrics-exporter-prometheus"]
compression = ["dep:async-compression"]
tls = ["dep:rustls", "dep:rustls-pemfile", "dep:tokio-rustls"]
websockets = ["dep:tokio-tungstenite"]
rate-limiting = ["dep:governor"]
jwt-auth = ["dep:jsonwebtoken"]

[[bench]]
name = "server_bench"
harness = false
